In [1]:
import numpy as np

In [11]:
numpyPrac_1 = np.arange(2*5).reshape(2,5).transpose()
print(numpyPrac_1)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [21]:
numpyPrac_2 = np.arange(10).astype('float32').transpose()
print(numpyPrac_2)
numpyPrac_2.shape
numpyPrac_2.dtype
print(numpyPrac_2[numpyPrac_2 > 5])

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[6. 7. 8. 9.]
